### ISSUE TITLE
Add new-window command functionality

### ISSUE THREAD

**Issue by ikirudennis** [tony/tmuxp#142]
Firstly, this project is pretty nice.

One feature of tmux I use frequently is the ability to start a new window with a command.  For instance, this is helpful with working in virtual environments in python.  I typically run `new-window -n name 'pew workon venv_name'` to launch a new window with the virtual environment activated.  This way, I don't have to exit twice to exit the window.  When I exit the venv, the command quits, and so does the window with it.

Other than that, you seem to have quite a lot of tmux's functionality covered.  Good job.

**Comment by kmactavish** [comment]
The code you added will only run the command once on building the workspace, after that, any new panes/windows won't be run with this command. This functionality was already available though `shell_command_before`.

Maybe you want to add tmux key bindings? That will let any new windows/panes you open run a given command when they open. 

In order to have the whole session live inside a virtual environment, including any new windows, you can use `tmuxp`'s `before_script`.

**Comment by kmactavish** [comment]
Moved my comment to #145, but I don't think there's any action to be taken by tmuxp to resolve this issue.

**Comment by tony** [comment]
Merged in #145
