### ISSUE TITLE
zsh - (eval):8: command not found: complete

### ISSUE THREAD

**Issue by rakanalh** [tony/tmuxp#190]
I am using Zsh and i've added 
`eval $(_TMUXP_COMPLETE=source tmuxp)` as in documentation. However, i get this error when i source my zshrc file.

Seems like complete is not compatible with zsh. The solution was to add:
```
autoload bashcompinit
bashcompinit
``` 
To my zshrc file, maybe that should be documented and/or a zsh compatible version of `complete` is provided.

Thanks

**Comment by von** [comment]
For zsh, I believe instead of:
> complete -F _tmuxp_completion -o default tmuxp;

we want:
> compdef _tmuxp_completion tmuxp;

**Comment by jonleopard** [comment]
@rakanalh Adding those two lines to my .zshrc file seemed to make the error message go away. Thanks for the tip!

**Comment by kuba-gaj** [comment]
Did not work for me (still no completion)
Is there proper way to make it work in zsh natively?

**Comment by lfilho** [comment]
Also having this problem.

Adding
```
autoload bashcompinit
bashcompinit
```
to my zshrc file didn't solve the issue but changed the error message to: `complete:13: command not found: compdef`.

Using zsh 5.3.1, tmuxp 1.3.1 and tmux 2.5

**Comment by tony** [comment]
I was concerned that the switch to click might make us lose control over completion. It did improve code quality and test coverage dramatically, though.

tmuxp's autocompletion facilities depends on autocompletion in click (http://click.pocoo.org/dev/bashcomplete/).

@lfilho I'm wondering if the ``command not found: compdef`` could be due to something else.

https://github.com/robbyrussell/oh-my-zsh/issues/3356

Can you try ``rm ~/.zcompdump*`` to see if that helps?

**Comment by lfilho** [comment]
Hey @tony thanks for trying to help me.

I read that entire thread and tried all suggestions but to no luck. I'm using prezto instead of oh-my-zsh though...

It's weird cause, naturally, I have working completion for many other commands and packages. `tmuxp` is the first one that gave me this error... :-/ I wonder what could it be

**Comment by ardeidae** [comment]
Hello,

Is there still no solution to this problem?

Adding:
```
autoload bashcompinit
bashcompinit
```

Give the error, too:
`complete:13: command not found: compdef`

Matthieu
