### ISSUE TITLE
Doesn't work with python-click > 6.6

### ISSUE THREAD

**Issue by rosshadden** [tony/tmuxp#198]
I get an error when trying to use `tmuxp` that makes me think it is requiring exactly click==6.6.  My system has click 6.7.1.

Here is the error:

![2017-01-10-10 07 45](https://cloud.githubusercontent.com/assets/669012/21811209/dd63c3c4-d71c-11e6-9c26-56db3d3adf25.png)

**Comment by thebopshoobop** [comment]
This error is fixed by [this commit](https://github.com/tony/tmuxp/commit/9c3d0dc16aced8ee4bff8f42725ddaeb3e265929). You can fix this problem by manually editing your local requires.txt file, which if you're running Arch is here: /usr/lib/python3.6/site-packages/tmuxp-1.2.3-py3.6.egg-info/. 

This is the second time this week that updated packages have caused tmuxp to stop working for me. I understand the utility of dependency pinning for development purposes and that tmuxp has a very short list of dependencies. However, the current situation is that whenever one of those dependencies is updated, no matter how trivial the update [(click 6.7 changed two non-functional lines)](https://github.com/pallets/click/commit/df0e37dd890d36fc997986ae6d2b6c255f3ed1dc), tmuxp is broken until a matching update in tmuxp can propagate through to end users. Might it be less user-hostile to have the dependencies be >= instead of ==?

**Comment by rosshadden** [comment]
@thebopshoobop Thanks, that did indeed work.  And I am running Arch, too :D.

I really do think it should be >=, but I'm kind of an outsider to the python package ecosystem, and not sure if they have good support for semver resolving.

**Comment by rosshadden** [comment]
Actually the fact that it's not even a semver version means no, at least in this case...  I guess I meant it more generally than semver, as in I don't know if python packages have a good solution for managing dependency versions.

**Comment by tony** [comment]
@rosshadden @thebopshoobop How is v1.2.4? Better?  Give it a shot and let me know

pyup.io did lock packages, but I'm not sure if it affected the release or not, as it happened after 1.2.3 was already tagged...

**Comment by thebopshoobop** [comment]
@tony v1.2.4 does indeed work just fine. Thanks for the speedy tag.
@rosshadden I've posted an updated PKGBUILD [here](https://gist.github.com/thebopshoobop/833aaf922e3d6187bbb123168a59d128), and I've flagged tmuxp out-of-date in the AUR.

**Comment by rosshadden** [comment]
@tony Yep, works great.  Thank you!
@thebopshoobop Good thinking.
